#!/bin/bash
### BEGIN INIT INFO
# Provides:          tunnelnamehere
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Tunnel Description Here
### END INIT INFO

TUNNELNAME="tunnelnamehere"
SSHHOST="example.com"
SSHHOST=$(/usr/local/bin/opendnsgetip ${SSHHOST})
SSHUSER="tunnel"
SSHPORT="9922"
TUNNELS=(
  "-R 0.0.0.0:4333:localhost:22"
  "-R 0.0.0.0:1294:localhost:1294"
)

###

AUTOSSH=`which autossh`

TUNNELS_STR=

count=0
while [ "x${TUNNELS[count]}" != "x" ]
do
   TUNNELS_STR="${TUNNELS_STR} ${TUNNELS[count]}"
   count=$(( $count + 1 ))
done

start() {
  $AUTOSSH -M 0 -N -T -f  $SSHUSER@$SSHHOST -p $SSHPORT $TUNNELS_STR -o "UserKnownHostsFile $TUNNELNAME" -o "StrictHostKeyChecking no" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" 
  echo "Service started" >&2
}

stop() {
  ps aux | grep "$TUNNELNAME" | grep ssh | awk '{print $2}' | xargs kill -9
  echo 'Service stopped' >&2
}

status() {
  ps aux | grep "$TUNNELNAME" | grep ssh | awk '{print $2}' | xargs echo
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
